Student: Dmytriv Artem
Group: CE-47
Subject: CSTD

Project name: Sea Battle game
Programming language: C, C++

Additional tools: Bash, Makefile
HW Interface: UART
Data driven format: XML

Play modes: Man vs Man, Man vs AI

Actions: New, Recover, Restart
The proposal for data driver approuch: game states, ship configurations, AI parameters.

Requirements:
1) Clone arduino-cmake scripts
git clone https://github.com/queezythegreat/arduino-cmake arduino-cmake
2) Get STL library
cd libraries
wget https://downloads.arduino.cc/libraries/github.com/mike-matera/ArduinoSTL-1.1.0.zip
unzip ArduinoSTL-1.1.0.zip